### ISSUE TITLE
Custom Build SyntaxError

### ISSUE THREAD

**Issue by evvvritt** [googleanalytics/autotrack#159]
Hi I'm trying to run the [custom build command](https://github.com/googleanalytics/autotrack#custom-builds) but it gives me a syntax error after installing globally via npm.

I used the example command from your Readme:

```
$ autotrack -o ~/Downloads/autotrack.custom.js -p eventTracker,outboundLinkTracker,urlChangeTracker
/usr/local/lib/node_modules/autotrack/bin/autotrack:44
  const {cyan, gray, green, red} = chalk;
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

Any help is much appreciated, Thanks!

**Comment by philipwalton** [comment]
It looks like it's failing on the ES2015 syntax, which probably means you're using an older version of node. Try upgrading to node 6+.
